"""Exercise library seed content — White Paper chapter 13.

Original content written from general, publicly available strength-training
knowledge (not copied from any commercial program or coach's materials —
see White Paper "Leeswijzer & scopeverklaring", bronmateriaal-beslissing).

Each entry: name, muscle (primary), secondary (list, optional), compound,
equipment, difficulty, description, tips (3), mistakes (3), is_main_lift,
alternatives (list of exercise names, resolved to IDs by seed.py).
"""

EXERCISES = [
    # ---------------------------------------------------------------- chest
    {
        "name": "Bench Press", "muscle": "chest", "secondary": ["triceps", "shoulders"],
        "compound": True, "equipment": "barbell", "difficulty": "intermediate",
        "is_main_lift": True,
        "description": "De basisoefening voor borstkracht: stang vanaf de borst omhoog drukken op een vlakke bank.",
        "tips": ["Trek schouderbladen samen en naar beneden", "Voeten stevig geplant op de grond",
                 "Stang raakt de onderborst, niet de hals"],
        "mistakes": ["Billen komen los van de bank", "Stang stuitert op de borst",
                     "Grip te breed of ongelijk links/rechts"],
        "alternatives": ["Incline Barbell Press", "Flat DB Press", "Machine Chest Press"],
    },
    {
        "name": "Incline Barbell Press", "muscle": "chest", "secondary": ["shoulders", "triceps"],
        "compound": True, "equipment": "barbell", "difficulty": "intermediate",
        "description": "Bench press op een schuine bank (30-45 graden) voor meer nadruk op de bovenborst.",
        "tips": ["Bankhoek niet hoger dan 45 graden (anders schouderdominant)", "Ellebogen ongeveer 45 graden t.o.v. romp",
                 "Stang naar de bovenborst, niet de hals"],
        "mistakes": ["Bank te steil ingesteld", "Onderrug overdreven hol",
                     "Reps te kort (stang niet laag genoeg)"],
        "alternatives": ["Incline DB Press", "Bench Press"],
    },
    {
        "name": "Incline DB Press", "muscle": "chest", "secondary": ["shoulders", "triceps"],
        "compound": True, "equipment": "dumbbell", "difficulty": "beginner",
        "description": "Dumbbell-variant van de incline press; groter bewegingsbereik dan de barbell-versie.",
        "tips": ["Dumbbells net onder schouderhoogte laten zakken", "Pols recht houden, niet naar achteren buigen",
                 "Lichte pauze onderin voor controle"],
        "mistakes": ["Dumbbells botsen bovenin", "Te snel excentrisch bewegen",
                     "Schouders komen omhoog richting oren"],
        "alternatives": ["Incline Barbell Press", "Flat DB Press"],
    },
    {
        "name": "Flat DB Press", "muscle": "chest", "secondary": ["triceps", "shoulders"],
        "compound": True, "equipment": "dumbbell", "difficulty": "beginner",
        "description": "Dumbbell bench press; toegankelijker instapvariant met vrij bewegingsbereik.",
        "tips": ["Dumbbells iets naar binnen kantelen bovenin", "Voeten plat op de grond voor stabiliteit",
                 "Onderin net zo diep als comfortabel is"],
        "mistakes": ["Ellebogen te ver uitgestrekt (verhoogt schouderbelasting)", "Core niet aangespannen",
                     "Ongelijke hoogte tussen links/rechts"],
        "alternatives": ["Bench Press", "Machine Chest Press"],
    },
    {
        "name": "Machine Chest Press", "muscle": "chest", "secondary": ["triceps"],
        "compound": True, "equipment": "machine", "difficulty": "beginner",
        "description": "Geleide borstpers; goede instapoefening of vermoeidheids-vriendelijk alternatief.",
        "tips": ["Stel de zithoogte zo in dat handvatten op borsthoogte staan", "Volledige rep, niet half",
                 "Rug plat tegen de rugleuning"],
        "mistakes": ["Zitting verkeerd afgesteld (te hoog/laag)", "Momentum gebruiken i.p.v. controle",
                     "Sloten te vroeg loslaten"],
        "alternatives": ["Flat DB Press", "Cable Fly"],
    },
    {
        "name": "Cable Fly", "muscle": "chest", "secondary": [],
        "compound": False, "equipment": "cable", "difficulty": "intermediate",
        "description": "Isolatiebeweging voor de borst via kabels, van hoog naar laag of vlak.",
        "tips": ["Lichte buiging in de ellebogen aanhouden", "Beweging komt uit de borst, niet de armen",
                 "Kruis handen licht bovenaan voor volledige contractie"],
        "mistakes": ["Ellebogen volledig gestrekt (belast gewrichten)", "Te zwaar gewicht wordt een pers",
                     "Romp niet stabiel, wiebelt mee"],
        "alternatives": ["Machine Chest Press", "Push-up"],
    },
    {
        "name": "Push-up", "muscle": "chest", "secondary": ["triceps", "shoulders", "abs"],
        "compound": True, "equipment": "bodyweight", "difficulty": "beginner",
        "description": "Klassieke lichaamsgewicht-oefening, overal uitvoerbaar zonder apparatuur.",
        "tips": ["Lichaam in een rechte lijn houden", "Handen iets breder dan schouderbreedte",
                 "Borst raakt bijna de grond"],
        "mistakes": ["Heupen zakken door", "Nek naar voren gestrekt",
                     "Halve reps zonder volledige uitstrekking"],
        "alternatives": ["Flat DB Press", "Machine Chest Press"],
    },
    {
        "name": "Decline Bench Press", "muscle": "chest", "secondary": ["triceps"],
        "compound": True, "equipment": "barbell", "difficulty": "advanced",
        "description": "Bench press op een dalende bank, nadruk op onderborst.",
        "tips": ["Voeten stevig verankerd onder de steunen", "Kortere ROM dan vlakke bench, niet forceren",
                 "Stang zakt naar de onderborst"],
        "mistakes": ["Te veel gewicht door kortere ROM", "Nek onder spanning door hoofdpositie",
                     "Ongecontroleerd naar beneden laten zakken"],
        "alternatives": ["Bench Press", "Cable Fly"],
    },
    {
        "name": "Dip (Chest-focused)", "muscle": "chest", "secondary": ["triceps", "shoulders"],
        "compound": True, "equipment": "bodyweight", "difficulty": "advanced",
        "description": "Dips met voorovergebogen romp voor borstnadruk, in plaats van rechtop voor triceps.",
        "tips": ["Romp voorover leunen voor borstfocus", "Ellebogen licht naar buiten",
                 "Onderin tot ongeveer 90 graden in de elleboog"],
        "mistakes": ["Te diep zakken bij weinig schoudermobiliteit", "Rechtop blijven (wordt tricep-dominant)",
                     "Schouders omhoog trekken richting oren"],
        "alternatives": ["Bench Press", "Cable Fly"],
    },

    # ----------------------------------------------------------------- back
    {
        "name": "Deadlift", "muscle": "back", "secondary": ["hamstrings", "glutes"],
        "compound": True, "equipment": "barbell", "difficulty": "advanced",
        "is_main_lift": True,
        "description": "Stang van de grond optillen tot volledige heupstrekking, de meest complete full-body lift.",
        "tips": ["Stang blijft dicht bij de schenen tijdens de trek", "Rug neutraal houden, niet ronden",
                 "Heupen en schouders komen tegelijk omhoog"],
        "mistakes": ["Onderrug rondt bij het optrekken", "Stang zwaait weg van het lichaam",
                     "Te vroeg met de heupen naar boven schieten"],
        "alternatives": ["Barbell Row", "Good Morning"],
    },
    {
        "name": "Barbell Row", "muscle": "back", "secondary": ["biceps", "shoulders"],
        "compound": True, "equipment": "barbell", "difficulty": "intermediate",
        "is_main_lift": True,
        "description": "Voorovergebogen roeibeweging met een barbell; bouwt dikte in de bovenrug.",
        "tips": ["Romp ongeveer 45 graden gebogen, vast gedurende de set", "Stang naar de onderbuik trekken",
                 "Schouderbladen samentrekken bovenaan"],
        "mistakes": ["Romp gaat rechtop staan tijdens de rep", "Onderrug rondt",
                     "Stang komt te hoog richting de borst"],
        "alternatives": ["Seated Cable Row", "T-Bar Row"],
    },
    {
        "name": "Pull-up", "muscle": "back", "secondary": ["biceps"],
        "compound": True, "equipment": "bodyweight", "difficulty": "advanced",
        "description": "Lichaamsgewicht optrekken aan een stang; een van de beste breedte-bouwers voor de rug.",
        "tips": ["Volledige hang onderin, kin boven de stang bovenin", "Schouderbladen eerst naar beneden trekken",
                 "Grip iets breder dan schouderbreedte"],
        "mistakes": ["Zwaaiende reps zonder controle", "Halve reps",
                     "Nek naar voren strekken om hoger te komen"],
        "alternatives": ["Lat Pulldown", "Straight-Arm Pulldown"],
    },
    {
        "name": "Lat Pulldown", "muscle": "back", "secondary": ["biceps"],
        "compound": True, "equipment": "cable", "difficulty": "beginner",
        "description": "Kabelvariant van de pull-up, schaalbaar in gewicht, goede opbouw naar pull-ups.",
        "tips": ["Stang naar de bovenborst trekken, niet de nek", "Lichte achterover leunen (10-20 graden)",
                 "Ellebogen naar beneden en licht naar achteren"],
        "mistakes": ["Te ver achterover leunen (wordt een row)", "Momentum met de romp",
                     "Stang achter de nek trekken"],
        "alternatives": ["Pull-up", "Seated Cable Row"],
    },
    {
        "name": "Seated Cable Row", "muscle": "back", "secondary": ["biceps"],
        "compound": True, "equipment": "cable", "difficulty": "beginner",
        "description": "Zittende roeibeweging aan de kabel; goed voor rugdikte met constante spanning.",
        "tips": ["Romp rechtop, licht bewegen mag", "Handvat naar de onderbuik trekken",
                 "Schouderbladen samentrekken aan het einde"],
        "mistakes": ["Overdreven achterover leunen met elke rep", "Ronde rug bij het vooroverbuigen",
                     "Alleen met de armen trekken"],
        "alternatives": ["Barbell Row", "Single-Arm DB Row"],
    },
    {
        "name": "T-Bar Row", "muscle": "back", "secondary": ["biceps", "shoulders"],
        "compound": True, "equipment": "machine", "difficulty": "intermediate",
        "description": "Roeibeweging met een vaste hendel; laat zware belasting toe met stabiele romp.",
        "tips": ["Romp vast in een hoek gedurende de hele set", "Handvat naar de borst/buik trekken",
                 "Volledige strekking onderin"],
        "mistakes": ["Romp komt omhoog tijdens het trekken", "Te korte ROM",
                     "Nek overstrekt om vooruit te kijken"],
        "alternatives": ["Barbell Row", "Seated Cable Row"],
    },
    {
        "name": "Single-Arm DB Row", "muscle": "back", "secondary": ["biceps"],
        "compound": True, "equipment": "dumbbell", "difficulty": "beginner",
        "description": "Eenzijdige roeibeweging, steunend met de andere hand op een bank.",
        "tips": ["Romp parallel aan de grond, stabiel", "Elleboog dicht langs het lichaam trekken",
                 "Volledige strekking onderin zonder de rug te ronden"],
        "mistakes": ["Romp draait mee met de trekbeweging", "Gebruik van momentum",
                     "Nek gedraaid richting de trekkende arm"],
        "alternatives": ["Seated Cable Row", "Barbell Row"],
    },
    {
        "name": "Face Pull", "muscle": "back", "secondary": ["shoulders"],
        "compound": False, "equipment": "cable", "difficulty": "beginner",
        "description": "Kabeltrek naar het gezicht; verstevigt achterste schouders en bovenrug, goed voor houding.",
        "tips": ["Touw naar het voorhoofd trekken, ellebogen hoog", "Externe rotatie aan het einde van de rep",
                 "Licht gewicht, focus op controle"],
        "mistakes": ["Te zwaar gewicht wordt een lat pulldown-beweging", "Ellebogen zakken naar beneden",
                     "Trekken met de onderarmen"],
        "alternatives": ["Straight-Arm Pulldown", "Rear Delt Fly"],
    },
    {
        "name": "Straight-Arm Pulldown", "muscle": "back", "secondary": ["abs"],
        "compound": False, "equipment": "cable", "difficulty": "intermediate",
        "description": "Kabelbeweging met gestrekte armen; isoleert de lats zonder biceps-betrokkenheid.",
        "tips": ["Armen bijna gestrekt gedurende de hele rep", "Beweging komt uit de schouders",
                 "Lichte voorover buiging in de heupen"],
        "mistakes": ["Ellebogen buigen tijdens de trek", "Te zwaar gewicht",
                     "Romp zwaait mee als momentum"],
        "alternatives": ["Lat Pulldown", "Face Pull"],
    },

    # ---------------------------------------------------------------- quads
    {
        "name": "Back Squat", "muscle": "quads", "secondary": ["glutes", "hamstrings"],
        "compound": True, "equipment": "barbell", "difficulty": "advanced",
        "is_main_lift": True,
        "description": "De koning der beenoefeningen: stang op de bovenrug, diep zakken en weer omhoog drukken.",
        "tips": ["Knieen volgen de richting van de tenen", "Borst hoog houden gedurende de hele beweging",
                 "Zak tot minstens heuphoogte parallel aan de grond"],
        "mistakes": ["Knieen vallen naar binnen", "Hielen komen los van de grond",
                     "Onderrug rondt onderin"],
        "alternatives": ["Front Squat", "Leg Press"],
    },
    {
        "name": "Front Squat", "muscle": "quads", "secondary": ["glutes", "abs"],
        "compound": True, "equipment": "barbell", "difficulty": "advanced",
        "description": "Squat met de stang vooraan op de schouders; meer quad-dominant, rechtopere romp.",
        "tips": ["Ellebogen hoog houden gedurende de squat", "Romp zo verticaal mogelijk",
                 "Gewicht op de hele voet, niet alleen de tenen"],
        "mistakes": ["Ellebogen zakken waardoor de stang naar voren rolt", "Te veel voorover leunen",
                     "Polsen overstrekt bij weinig mobiliteit"],
        "alternatives": ["Back Squat", "Hack Squat"],
    },
    {
        "name": "Leg Press", "muscle": "quads", "secondary": ["glutes"],
        "compound": True, "equipment": "machine", "difficulty": "beginner",
        "description": "Geleide beenpers; laat zware quad-belasting toe met minimale technische eisen.",
        "tips": ["Voeten schouderbreedte op de plaat", "Knieen niet volledig op slot laten komen bovenin",
                 "Onderrug blijft tegen de rugleuning"],
        "mistakes": ["Onderrug komt los van de rugleuning bij diep zakken", "Knieen op slot met veel gewicht",
                     "Te korte ROM"],
        "alternatives": ["Back Squat", "Hack Squat"],
    },
    {
        "name": "Leg Extension", "muscle": "quads", "secondary": [],
        "compound": False, "equipment": "machine", "difficulty": "beginner",
        "description": "Isolatiebeweging voor de quadriceps; goede finisher of opwarming voor de knie.",
        "tips": ["Korte pauze bovenaan voor volledige contractie", "Enkels op de rol, niet te hoog of laag",
                 "Gecontroleerd naar beneden, niet laten vallen"],
        "mistakes": ["Momentum gebruiken om het gewicht omhoog te zwiepen", "Volledig doorstrekken met een knal",
                     "Rug komt los van de rugleuning"],
        "alternatives": ["Leg Press", "Bulgarian Split Squat"],
    },
    {
        "name": "Bulgarian Split Squat", "muscle": "quads", "secondary": ["glutes"],
        "compound": True, "equipment": "dumbbell", "difficulty": "intermediate",
        "description": "Eenzijdige squat met achterste voet verhoogd; hoog rendement voor quads en balans.",
        "tips": ["Voorste knie boven de enkel houden", "Romp rechtop of licht voorover, niet ronden",
                 "Achterste voet alleen als steun, niet duwen"],
        "mistakes": ["Voorste knie schiet ver voorbij de tenen", "Te korte pas maakt het instabiel",
                     "Gewicht op de achterste voet leunen"],
        "alternatives": ["Walking Lunge", "Leg Extension"],
    },
    {
        "name": "Walking Lunge", "muscle": "quads", "secondary": ["glutes", "hamstrings"],
        "compound": True, "equipment": "dumbbell", "difficulty": "intermediate",
        "description": "Lopende longe met dumbbells; combineert kracht met balans en coordinatie.",
        "tips": ["Grote, gecontroleerde pas naar voren", "Romp rechtop houden", "Knie raakt bijna de grond"],
        "mistakes": ["Te kleine passen worden kniedominant", "Bovenlichaam valt voorover",
                     "Knie botst hard op de grond"],
        "alternatives": ["Bulgarian Split Squat", "Leg Press"],
    },
    {
        "name": "Hack Squat", "muscle": "quads", "secondary": ["glutes"],
        "compound": True, "equipment": "machine", "difficulty": "intermediate",
        "description": "Geleide squat-machine onder een hoek; quad-focus met minder balans-eisen dan vrije squat.",
        "tips": ["Voeten iets voor het midden van de plaat", "Onderrug plat tegen het kussen",
                 "Diepte tot comfortabele heupmobiliteit"],
        "mistakes": ["Te diep zakken met ronde onderrug", "Knieen naar binnen laten vallen",
                     "Sloten te vroeg loshalen"],
        "alternatives": ["Back Squat", "Leg Press"],
    },

    # ------------------------------------------------------------ hamstrings
    {
        "name": "Romanian Deadlift", "muscle": "hamstrings", "secondary": ["glutes", "back"],
        "compound": True, "equipment": "barbell", "difficulty": "intermediate",
        "description": "Heupscharnier met licht gebogen knieen; de basisoefening voor hamstrings en glutes.",
        "tips": ["Heupen naar achteren duwen, knieen blijven licht gebogen", "Stang blijft dicht bij de benen",
                 "Rek voelen in de hamstrings, niet in de onderrug"],
        "mistakes": ["Knieen buigen te veel (wordt een squat)", "Onderrug rondt",
                     "Stang zwaait weg van de benen"],
        "alternatives": ["Good Morning", "Lying Leg Curl"],
    },
    {
        "name": "Seated Leg Curl", "muscle": "hamstrings", "secondary": [],
        "compound": False, "equipment": "machine", "difficulty": "beginner",
        "description": "Isolatiebeweging voor de hamstrings in zittende positie.",
        "tips": ["Rugleuning zo instellen dat de knieen uitlijnen met de as", "Volledige contractie onderaan",
                 "Gecontroleerd terug naar de startpositie"],
        "mistakes": ["Heupen komen los van de zitting", "Momentum door mee te bewegen",
                     "Te beperkte ROM"],
        "alternatives": ["Lying Leg Curl", "Romanian Deadlift"],
    },
    {
        "name": "Lying Leg Curl", "muscle": "hamstrings", "secondary": [],
        "compound": False, "equipment": "machine", "difficulty": "beginner",
        "description": "Liggende variant van de leg curl; goede rek onderin de beweging.",
        "tips": ["Heupen plat op de bank houden", "Volledige curl richting de billen",
                 "Enkels niet overstrekt tijdens de beweging"],
        "mistakes": ["Heupen komen omhoog van de bank", "Te snel, ongecontroleerd terugveren",
                     "Rol te hoog of te laag op de kuiten"],
        "alternatives": ["Seated Leg Curl", "Romanian Deadlift"],
    },
    {
        "name": "Good Morning", "muscle": "hamstrings", "secondary": ["back", "glutes"],
        "compound": True, "equipment": "barbell", "difficulty": "advanced",
        "description": "Heupscharnier met stang op de bovenrug; sterke hamstring/onderrug-oefening, licht uitvoeren.",
        "tips": ["Begin licht, technisch veeleisende oefening", "Knieen licht gebogen, vast gedurende de set",
                 "Romp buigt voorover tot een lichte hamstring-rek"],
        "mistakes": ["Te zwaar te snel opbouwen", "Onderrug rondt tijdens het buigen",
                     "Te ver voorover buigen voorbij comfortabele mobiliteit"],
        "alternatives": ["Romanian Deadlift", "Seated Leg Curl"],
    },

    # ---------------------------------------------------------------- glutes
    {
        "name": "Hip Thrust", "muscle": "glutes", "secondary": ["hamstrings"],
        "compound": True, "equipment": "barbell", "difficulty": "intermediate",
        "description": "Heupextensie met de bovenrug op een bank; de meest directe glute-bouwer.",
        "tips": ["Kin naar de borst tijdens de lift", "Volledige heupextensie bovenaan, kort vasthouden",
                 "Stang rust op de heupplooi, gebruik een pad"],
        "mistakes": ["Onderrug overstrekt bovenaan i.p.v. de heupen", "Voeten te ver van het lichaam",
                     "Kin omhoog waardoor de nek overstrekt"],
        "alternatives": ["Glute Bridge", "Cable Pull-Through"],
    },
    {
        "name": "Glute Bridge", "muscle": "glutes", "secondary": ["hamstrings"],
        "compound": True, "equipment": "bodyweight", "difficulty": "beginner",
        "description": "Lichaamsgewicht- of licht belaste variant van de hip thrust, uitgevoerd op de grond.",
        "tips": ["Hielen dicht bij de billen plaatsen", "Knijp de billen samen bovenaan",
                 "Rug blijft neutraal, niet overstrekken"],
        "mistakes": ["Te weinig heupextensie", "Onderrug doet het werk i.p.v. de billen",
                     "Voeten te ver weg geplaatst"],
        "alternatives": ["Hip Thrust", "Cable Pull-Through"],
    },
    {
        "name": "Cable Pull-Through", "muscle": "glutes", "secondary": ["hamstrings"],
        "compound": True, "equipment": "cable", "difficulty": "intermediate",
        "description": "Heupscharnier met een kabel tussen de benen door; glute-vriendelijk met lage instap.",
        "tips": ["Heupen naar achteren, niet naar beneden", "Kabel blijft dicht bij het lichaam",
                 "Volledige heupextensie aan het einde"],
        "mistakes": ["Wordt een squat in plaats van heupscharnier", "Onderrug rondt bij het buigen",
                     "Te ver naar voren buigen"],
        "alternatives": ["Hip Thrust", "Romanian Deadlift"],
    },

    # ------------------------------------------------------------- shoulders
    {
        "name": "Overhead Press", "muscle": "shoulders", "secondary": ["triceps", "abs"],
        "compound": True, "equipment": "barbell", "difficulty": "intermediate",
        "is_main_lift": True,
        "description": "Stang vanaf de schouders recht omhoog drukken, staand, de basis voor schouderkracht.",
        "tips": ["Core stevig aanspannen tijdens de druk", "Stang beweegt in een rechte lijn omhoog",
                 "Hoofd licht naar achteren zodra de stang passeert"],
        "mistakes": ["Onderrug overdreven hol trekken", "Stang zwaait naar voren i.p.v. recht omhoog",
                     "Benen actief meeduwen"],
        "alternatives": ["Seated DB Shoulder Press", "Arnold Press"],
    },
    {
        "name": "Seated DB Shoulder Press", "muscle": "shoulders", "secondary": ["triceps"],
        "compound": True, "equipment": "dumbbell", "difficulty": "beginner",
        "description": "Zittende schouderpers met dumbbells; stabiele instapoefening voor schouderkracht.",
        "tips": ["Rugleuning ondersteunt de onderrug", "Dumbbells starten op schouderhoogte",
                 "Niet volledig op slot drukken met de ellebogen"],
        "mistakes": ["Onderrug hol trekken zonder steun", "Dumbbells botsen bovenin",
                     "Polsen naar achteren geknikt"],
        "alternatives": ["Overhead Press", "Arnold Press"],
    },
    {
        "name": "Lateral Raise", "muscle": "shoulders", "secondary": [],
        "compound": False, "equipment": "dumbbell", "difficulty": "beginner",
        "description": "Zijwaartse heffing voor de zijkant van de schouder; bepaalt schouderbreedte.",
        "tips": ["Lichte buiging in de ellebogen", "Til tot ongeveer schouderhoogte, niet hoger",
                 "Beweging vanuit de schouder, niet de onderarm"],
        "mistakes": ["Momentum met de romp", "Te zwaar gewicht wordt een shrug",
                     "Handen komen boven de ellebogen"],
        "alternatives": ["Cable Lateral Raise", "Arnold Press"],
    },
    {
        "name": "Cable Lateral Raise", "muscle": "shoulders", "secondary": [],
        "compound": False, "equipment": "cable", "difficulty": "intermediate",
        "description": "Kabelvariant van de lateral raise; constante spanning door het hele bewegingsbereik.",
        "tips": ["Kabel aan de laagste positie bevestigen", "Lichte voorover leunen weg van de kabel",
                 "Til tot schouderhoogte, gecontroleerd terug"],
        "mistakes": ["Romp draait mee als momentum", "Te zwaar met onvolledige ROM",
                     "Pols leidt de beweging"],
        "alternatives": ["Lateral Raise", "Rear Delt Fly"],
    },
    {
        "name": "Rear Delt Fly", "muscle": "shoulders", "secondary": ["back"],
        "compound": False, "equipment": "dumbbell", "difficulty": "beginner",
        "description": "Voorovergebogen zijheffing voor de achterste schouder; belangrijk voor schouderbalans.",
        "tips": ["Romp voorover ongeveer 45 graden, rug neutraal", "Lichte buiging in de ellebogen, vast",
                 "Beweging komt uit de achterste schouder"],
        "mistakes": ["Romp komt omhoog tijdens de rep", "Te zwaar gewicht wordt een row",
                     "Ellebogen volledig gestrekt"],
        "alternatives": ["Face Pull", "Cable Lateral Raise"],
    },
    {
        "name": "Arnold Press", "muscle": "shoulders", "secondary": ["triceps"],
        "compound": True, "equipment": "dumbbell", "difficulty": "intermediate",
        "description": "Schouderpers met een roterende beweging, met een draai tijdens de druk.",
        "tips": ["Start met palmen naar het lichaam gericht", "Draai geleidelijk tijdens het omhoog drukken",
                 "Volledige rotatie bovenaan, palmen naar voren"],
        "mistakes": ["Draai te snel/abrupt uitgevoerd", "Onderrug hol trekken",
                     "Gewicht te zwaar voor gecontroleerde rotatie"],
        "alternatives": ["Seated DB Shoulder Press", "Overhead Press"],
    },
    {
        "name": "Upright Row", "muscle": "shoulders", "secondary": ["biceps"],
        "compound": True, "equipment": "barbell", "difficulty": "intermediate",
        "description": "Stang langs het lichaam omhoog trekken tot borsthoogte; traint zijdelen en trapezius.",
        "tips": ["Ellebogen leiden de beweging, hoger dan de handen", "Stang blijft dicht bij het lichaam",
                 "Til tot ongeveer borsthoogte"],
        "mistakes": ["Te hoog trekken", "Grip te smal",
                     "Momentum met de romp"],
        "alternatives": ["Lateral Raise", "Cable Lateral Raise"],
    },

    # --------------------------------------------------------------- biceps
    {
        "name": "Barbell Curl", "muscle": "biceps", "secondary": [],
        "compound": False, "equipment": "barbell", "difficulty": "beginner",
        "description": "De klassieke bicepscurl met een rechte of EZ-stang.",
        "tips": ["Ellebogen dicht bij het lichaam, vast gedurende de set", "Volledige strekking onderin",
                 "Knijp bovenaan de biceps samen"],
        "mistakes": ["Momentum met de romp", "Ellebogen zwaaien naar voren",
                     "Halve reps zonder volledige strekking"],
        "alternatives": ["DB Curl", "Cable Curl"],
    },
    {
        "name": "DB Curl", "muscle": "biceps", "secondary": [],
        "compound": False, "equipment": "dumbbell", "difficulty": "beginner",
        "description": "Bicepscurl met dumbbells, afwisselend of gelijktijdig.",
        "tips": ["Volledige rotatie naar boven tijdens de curl", "Ellebogen blijven op een vaste plek",
                 "Gecontroleerd naar beneden, niet laten vallen"],
        "mistakes": ["Schouders zwaaien mee als momentum", "Polsen buigen tijdens de curl",
                     "Te zwaar gewicht geeft een halve rep"],
        "alternatives": ["Hammer Curl", "Barbell Curl"],
    },
    {
        "name": "Hammer Curl", "muscle": "biceps", "secondary": [],
        "compound": False, "equipment": "dumbbell", "difficulty": "beginner",
        "description": "Curl met neutrale handgreep (duimen omhoog); traint ook de onderarm mee.",
        "tips": ["Handgreep blijft neutraal gedurende de hele rep", "Ellebogen dicht bij het lichaam",
                 "Volledige strekking onderin"],
        "mistakes": ["Pols draait alsnog mee", "Momentum met de schouders",
                     "Ellebogen komen los van het lichaam"],
        "alternatives": ["DB Curl", "Cable Curl"],
    },
    {
        "name": "Cable Curl", "muscle": "biceps", "secondary": [],
        "compound": False, "equipment": "cable", "difficulty": "beginner",
        "description": "Curl aan de kabel voor constante spanning door het hele bewegingsbereik.",
        "tips": ["Ellebogen vast naast het lichaam", "Constante spanning, geen pauze onderin",
                 "Knijp bovenaan even vast"],
        "mistakes": ["Romp leunt naar achteren als momentum", "Ellebogen zwaaien naar voren",
                     "Te snel tempo zonder controle"],
        "alternatives": ["Barbell Curl", "Preacher Curl"],
    },
    {
        "name": "Preacher Curl", "muscle": "biceps", "secondary": [],
        "compound": False, "equipment": "machine", "difficulty": "intermediate",
        "description": "Curl met de arm ondersteund op een schuin kussen; isoleert de biceps door momentum uit te sluiten.",
        "tips": ["Oksels goed tegen het kussen aan", "Volledige strekking onderin, rustig",
                 "Niet volledig doorstrekken met een knal"],
        "mistakes": ["Schouders komen los van het kussen", "Te snel onderin",
                     "Halve reps bovenin"],
        "alternatives": ["Incline DB Curl", "Cable Curl"],
    },
    {
        "name": "Incline DB Curl", "muscle": "biceps", "secondary": [],
        "compound": False, "equipment": "dumbbell", "difficulty": "intermediate",
        "description": "Curl liggend op een schuine bank; extra rek op de biceps door de armpositie naar achteren.",
        "tips": ["Schouders blijven naar achteren tegen de bank", "Volledige strekking onderin voor de rek",
                 "Ellebogen bewegen niet naar voren"],
        "mistakes": ["Schouders komen los van de bank", "Ellebogen zwaaien naar voren",
                     "Te zwaar voor de verlengde hefboom"],
        "alternatives": ["DB Curl", "Preacher Curl"],
    },

    # -------------------------------------------------------------- triceps
    {
        "name": "Cable Pushdown", "muscle": "triceps", "secondary": [],
        "compound": False, "equipment": "cable", "difficulty": "beginner",
        "description": "Tricepsextensie aan de kabel, staand met touw of rechte stang.",
        "tips": ["Ellebogen vast naast het lichaam", "Volledige strekking onderin",
                 "Romp rechtop, niet voorover leunen als hulp"],
        "mistakes": ["Ellebogen bewegen naar voren/achteren", "Romp leunt voorover als momentum",
                     "Polsen buigen mee bij de touw-variant"],
        "alternatives": ["Skull Crusher", "Overhead Triceps Extension"],
    },
    {
        "name": "Skull Crusher", "muscle": "triceps", "secondary": [],
        "compound": False, "equipment": "barbell", "difficulty": "intermediate",
        "description": "Liggende tricepsextensie met een barbell of EZ-stang naar het voorhoofd.",
        "tips": ["Ellebogen blijven op een vaste plek, wijzen naar het plafond", "Stang zakt gecontroleerd richting voorhoofd",
                 "Volledige strekking bovenin"],
        "mistakes": ["Ellebogen zwaaien naar buiten/binnen", "Te zwaar gewicht bij deze elleboog-gevoelige oefening",
                     "Onvolledige ROM"],
        "alternatives": ["Cable Pushdown", "Overhead Triceps Extension"],
    },
    {
        "name": "Overhead Triceps Extension", "muscle": "triceps", "secondary": [],
        "compound": False, "equipment": "dumbbell", "difficulty": "intermediate",
        "description": "Tricepsextensie boven het hoofd; goede rek door de lange kop van de triceps.",
        "tips": ["Ellebogen wijzen naar voren, dicht bij het hoofd", "Onderrug niet overdreven hol trekken",
                 "Volledige strekking bovenin zonder de ellebogen op slot te knallen"],
        "mistakes": ["Ellebogen zwaaien naar buiten", "Onderrug compenseert",
                     "Te zwaar voor gecontroleerde uitvoering"],
        "alternatives": ["Skull Crusher", "Cable Pushdown"],
    },
    {
        "name": "Close-Grip Bench Press", "muscle": "triceps", "secondary": ["chest", "shoulders"],
        "compound": True, "equipment": "barbell", "difficulty": "intermediate",
        "description": "Bench press met smalle grip; verschuift de nadruk van borst naar triceps.",
        "tips": ["Grip ongeveer schouderbreedte, niet extreem smal", "Ellebogen dicht bij het lichaam tijdens de druk",
                 "Stang naar de onderborst"],
        "mistakes": ["Grip te smal (polsbelastend)", "Ellebogen wijzen naar buiten",
                     "Stang stuitert op de borst"],
        "alternatives": ["Cable Pushdown", "Bench Press"],
    },
    {
        "name": "Bench Dip", "muscle": "triceps", "secondary": ["shoulders"],
        "compound": True, "equipment": "bodyweight", "difficulty": "beginner",
        "description": "Dip met handen op een bank en voeten op de grond; toegankelijke tricepsoefening.",
        "tips": ["Heupen dicht bij de bank tijdens het zakken", "Ellebogen wijzen naar achteren, niet naar buiten",
                 "Niet te diep zakken bij schouderklachten"],
        "mistakes": ["Heupen te ver van de bank", "Te diep zakken zonder controle",
                     "Schouders omhoog trekken richting oren"],
        "alternatives": ["Cable Pushdown", "Close-Grip Bench Press"],
    },

    # --------------------------------------------------------------- calves
    {
        "name": "Standing Calf Raise", "muscle": "calves", "secondary": [],
        "compound": False, "equipment": "machine", "difficulty": "beginner",
        "description": "Kuitheffing staand, met gestrekte knieen, traint vooral de gastrocnemius.",
        "tips": ["Volledige rek onderaan (hielen laag)", "Korte pauze bovenaan op de tenen",
                 "Gecontroleerd tempo, niet stuiteren"],
        "mistakes": ["Halve reps met beperkte ROM", "Stuiteren onderin i.p.v. controle",
                     "Knieen buigen mee tijdens de beweging"],
        "alternatives": ["Seated Calf Raise", "Donkey Calf Raise"],
    },
    {
        "name": "Seated Calf Raise", "muscle": "calves", "secondary": [],
        "compound": False, "equipment": "machine", "difficulty": "beginner",
        "description": "Kuitheffing zittend met gebogen knieen, verschuift de nadruk naar de soleus.",
        "tips": ["Knieen in een vaste hoek van ongeveer 90 graden", "Volledige rek onderin en contractie bovenin",
                 "Gecontroleerd tempo door de hele rep"],
        "mistakes": ["Beperkte ROM met halve reps", "Te snel tempo zonder pauze bovenaan",
                     "Kussen verkeerd afgesteld op de knieen"],
        "alternatives": ["Standing Calf Raise", "Donkey Calf Raise"],
    },
    {
        "name": "Donkey Calf Raise", "muscle": "calves", "secondary": [],
        "compound": False, "equipment": "machine", "difficulty": "intermediate",
        "description": "Kuitheffing voorovergebogen; grotere rek onderin dan de staande variant.",
        "tips": ["Romp stabiel voorovergebogen", "Volledige rek onderaan voelen in de kuit",
                 "Bovenaan even vasthouden voor maximale contractie"],
        "mistakes": ["Rug rondt tijdens de beweging", "Stuiteren onderin",
                     "Beperkte ROM door onvoldoende diep te zakken"],
        "alternatives": ["Standing Calf Raise", "Seated Calf Raise"],
    },

    # ------------------------------------------------------------------ abs
    {
        "name": "Cable Crunch", "muscle": "abs", "secondary": [],
        "compound": False, "equipment": "cable", "difficulty": "beginner",
        "description": "Geknielde crunch aan de kabel; laat progressieve belasting toe op de buikspieren.",
        "tips": ["Beweging komt uit de buik, niet de heupen", "Heupen blijven stil tijdens de beweging",
                 "Volledige contractie onderin, ellebogen richting knieen"],
        "mistakes": ["Heupen bewegen mee met de crunch", "Trekken met de armen i.p.v. de buik",
                     "Te zwaar gewicht geeft onvolledige ROM"],
        "alternatives": ["Hanging Leg Raise", "Weighted Sit-up"],
    },
    {
        "name": "Hanging Leg Raise", "muscle": "abs", "secondary": [],
        "compound": False, "equipment": "bodyweight", "difficulty": "advanced",
        "description": "Benen optrekken hangend aan een stang; traint vooral de onderbuik.",
        "tips": ["Bekken kantelen bovenaan de beweging", "Gecontroleerd, geen swing",
                 "Benen zo gestrekt mogelijk voor meer moeilijkheid"],
        "mistakes": ["Swingen met het hele lichaam", "Alleen heupen buigen zonder bekkenkanteling",
                     "Te snel tempo zonder controle"],
        "alternatives": ["Cable Crunch", "Ab Wheel Rollout"],
    },
    {
        "name": "Plank", "muscle": "abs", "secondary": ["shoulders"],
        "compound": True, "equipment": "bodyweight", "difficulty": "beginner",
        "description": "Isometrische core-oefening; bouwt stabiliteit en anti-extensie kracht.",
        "tips": ["Lichaam in een rechte lijn van hoofd tot hielen", "Billen lichtjes aanspannen",
                 "Adem rustig door blijven halen"],
        "mistakes": ["Heupen zakken door", "Heupen te hoog waardoor het minder effectief wordt",
                     "Adem inhouden tijdens de hold"],
        "alternatives": ["Ab Wheel Rollout", "Cable Crunch"],
    },
    {
        "name": "Ab Wheel Rollout", "muscle": "abs", "secondary": ["shoulders"],
        "compound": True, "equipment": "bodyweight", "difficulty": "advanced",
        "description": "Uitrollen met een ab-wheel vanaf de knieen; zware anti-extensie core-oefening.",
        "tips": ["Bekken lichtjes gekanteld gedurende de hele beweging", "Zo ver rollen als je zonder doorzakken kunt",
                 "Kom terug met de buik, niet met de heupen als eerste"],
        "mistakes": ["Onderrug zakt door", "Te ver rollen zonder kracht om terug te komen",
                     "Alleen de armen gebruiken i.p.v. de core"],
        "alternatives": ["Plank", "Hanging Leg Raise"],
    },
    {
        "name": "Russian Twist", "muscle": "abs", "secondary": [],
        "compound": False, "equipment": "bodyweight", "difficulty": "beginner",
        "description": "Draaiende rompbeweging zittend; traint de schuine buikspieren.",
        "tips": ["Romp achterover onder een hoek van ongeveer 45 graden", "Draai vanuit de romp, niet alleen de armen",
                 "Voeten van de grond voor extra moeilijkheid (optioneel)"],
        "mistakes": ["Te snel tempo zonder controle", "Draai komt alleen uit de armen",
                     "Onderrug rondt tijdens het achterover leunen"],
        "alternatives": ["Cable Crunch", "Plank"],
    },
    {
        "name": "Weighted Sit-up", "muscle": "abs", "secondary": [],
        "compound": False, "equipment": "dumbbell", "difficulty": "intermediate",
        "description": "Sit-up met extra gewicht tegen de borst voor progressieve belasting.",
        "tips": ["Voeten verankerd of ondersteund", "Beweging begint met de kin naar de borst",
                 "Gecontroleerd zakken, niet laten vallen"],
        "mistakes": ["Trekken aan de nek met de handen", "Momentum gebruiken",
                     "Onderrug overbelast bij te zwaar gewicht"],
        "alternatives": ["Cable Crunch", "Hanging Leg Raise"],
    },
]
