"""add suggested_from_wod_id to workouts

Revision ID: 595ecbad8f28
Revises: 
Create Date: 2026-07-27 08:23:54.267723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595ecbad8f28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_from_wod_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('suggested_from_wod_id')

    # ### end Alembic commands ###
