"""initial schema

Revision ID: bbce568ba628
Revises: 
Create Date: 2026-07-25 14:46:19.020433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbce568ba628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('muscle_groups',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('bodyweight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('global_goal', sa.String(length=12), nullable=False),
    sa.Column('experience', sa.String(length=12), nullable=True),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=True),
    sa.Column('session_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('training_location', sa.String(length=10), nullable=True),
    sa.Column('unit_preference', sa.String(length=3), nullable=True),
    sa.Column('deload_active', sa.Boolean(), nullable=False),
    sa.Column('last_deload_at', sa.Date(), nullable=True),
    sa.Column('sleep_score', sa.SmallInteger(), nullable=True),
    sa.Column('stress_score', sa.SmallInteger(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("experience IN ('beginner','intermediate','advanced')", name='ck_users_experience'),
    sa.CheckConstraint("global_goal IN ('hypertrophy','strength')", name='ck_users_goal'),
    sa.CheckConstraint('age BETWEEN 16 AND 100', name='ck_users_age'),
    sa.CheckConstraint('days_per_week BETWEEN 1 AND 7', name='ck_users_days'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exercises',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('primary_muscle_id', sa.Integer(), nullable=False),
    sa.Column('is_compound', sa.Boolean(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=12), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technique_tips', sa.Text(), nullable=True),
    sa.Column('common_mistakes', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('is_main_lift', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['primary_muscle_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'created_by', name='uq_exercise_name_owner')
    )
    op.create_table('user_equipment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'equipment_id', name='uq_user_equipment')
    )
    op.create_table('warnings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warning_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_hint', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('manual','suggested')", name='ck_workouts_source'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index('ix_workouts_user_performed', ['user_id', 'performed_at'], unique=False)

    op.create_table('exercise_alternatives',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alternative_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'alternative_id', name='uq_exercise_alternative')
    )
    op.create_table('exercise_secondary_muscles',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'muscle_group_id', name='uq_exercise_secondary')
    )
    op.create_table('periodization_blocks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('weeks', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_avoided_exercises',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_user_avoided')
    )
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'position', name='uq_workout_position')
    )
    op.create_table('sets',
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reps', sa.SmallInteger(), nullable=False),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('tempo', sa.String(length=10), nullable=True),
    sa.Column('tut_sec', sa.SmallInteger(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reps BETWEEN 1 AND 100', name='ck_sets_reps'),
    sa.CheckConstraint('rpe BETWEEN 1 AND 10', name='ck_sets_rpe'),
    sa.CheckConstraint('weight_kg >= 0', name='ck_sets_weight'),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sets_workout_exercise_id'), ['workout_exercise_id'], unique=False)

    op.create_table('e1rm_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('e1rm_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source_set_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['source_set_id'], ['sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('e1rm_history', schema=None) as batch_op:
        batch_op.create_index('ix_e1rm_user_exercise_date', ['user_id', 'exercise_id', 'date'], unique=False)

    op.create_table('personal_records',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=12), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('achieved_at', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("record_type IN ('weight','reps','e1rm','tonnage')", name='ck_pr_type'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', 'record_type', name='uq_pr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_records')
    with op.batch_alter_table('e1rm_history', schema=None) as batch_op:
        batch_op.drop_index('ix_e1rm_user_exercise_date')

    op.drop_table('e1rm_history')
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sets_workout_exercise_id'))

    op.drop_table('sets')
    op.drop_table('workout_exercises')
    op.drop_table('user_avoided_exercises')
    op.drop_table('periodization_blocks')
    op.drop_table('exercise_secondary_muscles')
    op.drop_table('exercise_alternatives')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index('ix_workouts_user_performed')

    op.drop_table('workouts')
    op.drop_table('warnings')
    op.drop_table('user_equipment')
    op.drop_table('exercises')
    op.drop_table('users')
    op.drop_table('muscle_groups')
    op.drop_table('equipment')
    # ### end Alembic commands ###
